site_name: GraphicsLab Documentation
theme:
  name: material

nav:
  - Home: index.md
  - GraphicsLab:
      - Get Started: graphicslab/get_started.md
  - Language:
      - Overview: language/language.md
      - Reflection: language/refelction.md
      - Parallel: language/parallel.md
  - Rendering:
      - Scene: rendering/scene.md
  - Numeric:
      - Polynomial Solver: numeric/polynomial_solver.md
  - Geometry:
      - Introduction: geometry/introduction.md
      - Parametric Geometry:
          - Curves:
              - Base Curves: geometry/parametric geometry/curves/base_curves.md
              - Analytic Curves: geometry/parametric geometry/curves/analytic_curves.md
              - Bezier Curves: geometry/parametric geometry/curves/bezier_curves.md
          - Surfaces:
              - Base Surface: geometry/parametric geometry/surfaces/base_surface.md
              - Analytic Surfaces: geometry/parametric geometry/surfaces/analytic_surfaces.md
              - Explicit Surfaces: geometry/parametric geometry/surfaces/explicit_surfaces.md
      - Boundary Representation:
          - Topology Definition: geometry/boundary representation/topology_definition.md
          - Intersectors: geometry/boundary representation/intersector/intersectors.md
          - Surface-Surface Intersection: geometry/boundary representation/intersector/surface_surface_intersection.md
          - Plane-Torus Intersection: geometry/boundary representation/intersector/plane_torus_intersection.md
          - Boolean Operations: geometry/boundary representation/boolean_operations.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
